import { Smartphone, ShieldCheck, Layers, type LucideIcon } from 'lucide-react';

export const RAW_EXPERIENCE_TEXT = `SYSTEM INITIALIZATION SEQUENCE STARTED. IDENTITY CONFIRMED: LIAM FAN. DESIGNATION: FULL-STACK INDIE BUILDER, FORMER IOS ARCHITECT, EX-TECHNICAL DIRECTOR. EXPERIENCE METRIC: 14+ YEARS OF UNINTERRUPTED SOFTWARE ENGINEERING EXPERTISE. TRAJECTORY: EVOLVED FROM WRITING FRONTLINE LOW-LEVEL OBJECTIVE-C CODE TO ORCHESTRATING LARGE-SCALE DISTRIBUTED SYSTEMS, AND NOW PIONEERING AI-NATIVE ARCHITECTURES AS A SOLO FOUNDER. HISTORICAL LOG: SPEARHEADED A 30-PERSON CROSS-PLATFORM ENGINEERING MATRIX AT PING AN GROUP. DIRECTED THE CORE ARCHITECTURE REBUILD FOR A FINTECH FLAGSHIP PLATFORM SCALING WELL BEYOND 4 MILLION PEAK DAILY ACTIVE USERS. NAVIGATED HIGH-CONCURRENCY BOTTLENECKS DURING CRITICAL FINANCIAL TRANSACTIONS. PIONEERED ZERO-DAY HOT-FIX MECHANISMS USING DYNAMIC FRAMEWORK INJECTION, COMPRESSING CRITICAL VULNERABILITY RESOLUTION WINDOWS FROM WEEKS TO UNDER TWO HOURS. IMPLEMENTED ADVANCED GREY-BOX RELEASE PIPELINES AND AUTOMATED A/B TESTING INFRASTRUCTURE THAT PLUMMETED PRODUCTION ROLLBACK RATES BY 50 PERCENT. CHAMPIONED MODULAR COMPONENTIZATION, REDUCING BUILD TIMES BY 40 PERCENT AND ELIMINATING SPAGHETTI CODE DEPENDENCIES ACROSS MULTIPLE REPOSITORIES. CURRENT OPERATIONAL PHILOSOPHY: ZERO BLOATED ARCHITECTURES. I REJECT OVER-ENGINEERING IN FAVOR OF PRAGMATIC, DETERMINISTIC MVP DELIVERY. NO TRANSLATION LOST BETWEEN BUSINESS OBJECTIVES AND TECHNICAL WORK BREAKDOWN STRUCTURES. I MERGE A STRICT DESIGN-TO-CODE PIPELINE. I TRANSFORM HIGH-FIDELITY UI PROTOTYPES FROM SKETCH AND FIGMA DIRECTLY INTO PRODUCTION-READY BACKEND LOGIC AND PIXEL-PERFECT FRONTEND INTERFACES. THIS BROWSER-TO-DATABASE CONTINUITY ELIMINATES CROSS-DEPARTMENTAL FRICTION, REDUCES COMMUNICATION OVERHEAD, AND ACCELERATES TIME-TO-MARKET. I PRACTICE HONEST ESTIMATION. HAVING EXPERIENCED REAL-WORLD PROJECT FAILURES AND SCOPE CREEP, I RUTHLESSLY STRIP AWAY PSEUDO-NEEDS AND PREVENT EXPENSIVE TECHNICAL DEBT BEFORE A SINGLE LINE OF CODE IS COMMITTED. RECENT ENGINEERING LOGS - CASE ALPHA: THE GAAP MULTI-CURRENCY FINANCIAL SYSTEM. THIS IS NOT MERELY AN ACCOUNTING TOOL; IT IS A STRESS TEST OF THE LIMITS OF LLM VIBE CODING AND GENERATIVE AI WORKFLOWS. RATHER THAN BLINDLY TRUSTING NON-DETERMINISTIC AI OUTPUTS, I ARCHITECTED A DEFENSIVE BACKEND POSTURE. THE SYSTEM TAMED AI HALLUCINATIONS BY ENFORCING STRICT GOLANG TYPE SYSTEMS, INTERFACE CONTRACTS, AND PROPERTY-BASED MATHEMATICAL TESTING. I BUILT IMPENETRABLE GUARDRAILS ENSURING THAT ACID TRANSACTIONS, DOUBLE-ENTRY BOOKKEEPING RULES, GRPC MICROSERVICE COMMUNICATIONS, AND PROTOBUF SERIALIZATION REMAINED BULLETPROOF, EVEN WHEN THE AI ASSISTANT ATTEMPTED TO GENERATE FLAWED OR INCOMPLETE ACCOUNTING LOGIC. CASE BETA: ENTERPRISE-GRADE AI INFRASTRUCTURE DEPLOYMENTS. EXECUTED A HIGH-STAKES DIFY PLATFORM CUSTOMIZATION AND ON-PREMISE INTEGRATION FOR AUTOMOTIVE SECTOR CLIENTS. DESIGNED A HIGH-AVAILABILITY GLOBAL SINGLE SIGN-ON GATEWAY AND ROLE-BASED ACCESS CONTROL REVERSE PROXY ARCHITECTURE SCALING TO THOUSANDS OF INTERNAL USERS. DECOUPLED THE AUTHENTICATION LAYER FROM THE CORE AI ENGINE. ACHIEVED DYNAMIC SYNCHRONIZATION OF USER MASTER DATA DIRECTLY WITH ACTIVE DIRECTORY. THIS ENABLED HIGHLY SECURE, INTRANET-GAPPED AI DEPLOYMENT, ENSURING ENTERPRISE DATA PRIVACY COMPLIANCE WITH MINIMAL INTRUSION INTO THE UPSTREAM OPEN-SOURCE CODEBASE. CASE GAMMA: PRODUCTION-READY RAG PIPELINES FOR CONSUMER-FACING AI APPLICATIONS, SPECIFICALLY IN THE DOMAIN OF PSYCHOLOGICAL DREAM ANALYSIS. ENGINEERED DUAL-MODEL DYNAMIC ROUTING TO OPTIMIZE INFERENCE COSTS AND LATENCY ACROSS TOP-TIER LLMS. INTEGRATED FASTAPI, TXTAI FOR LOCALIZED EMBEDDINGS, AND CUSTOM JIEBA TOKENIZATION ALGORITHMS. THIS PIPELINE ACHIEVED LIGHTWEIGHT YET HIGHLY ACCURATE VECTOR RETRIEVAL UNDER CONSTRAINED COMPUTE ENVIRONMENTS, OUTPERFORMING STANDARD OUT-OF-THE-BOX VECTOR DATABASES IN BOTH LATENCY AND RESOURCE CONSUMPTION. IMPLEMENTED SEMANTIC CACHING TO REDUCE REDUNDANT API CALLS BY 30 PERCENT. CASE DELTA: SOLVING EXTREME RENDERING INCONSISTENCIES FOR THEATRICAL ARTS CLIENTS. DELIVERED A HIGH-PERFORMANCE, CROSS-PLATFORM DRAG-AND-DROP POSTER EDITOR AIMED EXCLUSIVELY AT MOBILE DEVICES. AVOIDED THE TRAP OF FLAWED PURE-FRONTEND DOM-TO-IMAGE RENDERING WHICH SUFFERS FROM DEVICE-SPECIFIC CSS QUIRKS. INSTEAD, I ARCHITECTED A DETERMINISTIC HYBRID SOLUTION. UTILIZED THE WECHAT MINIPROGRAM CANVAS API FOR FLUID, 60FPS UI INTERACTION, COUPLED WITH A HIGH-THROUGHPUT GOLANG BACKEND UTILIZING THE STANDARD IMAGE LIBRARY FOR PIXEL-PERFECT, DEVICE-AGNOSTIC IMAGE COMPOSITING AND EXPORT. ZERO RESOLUTION INDUCED LAYOUT BUGS ON PRODUCTION. HISTORICAL ARCHIVE: EARLY CAREER HIGHLIGHTS INCLUDE REFACTORING CRUMBLING LEGACY INSURANCE PLATFORMS FOR AIA GROUP. EXECUTED A HIGH-RISK RIP-AND-REPLACE STRATEGY, MIGRATING OUTDATED PHONEGAP HYBRID FRAMEWORKS TO FULLY NATIVE ARCHITECTURES WITH ZERO RELIANCE ON NON-EXISTENT DOCUMENTATION. REVERSE-ENGINEERED OBFUSCATED BUSINESS LOGIC. RESOLVED SEVERE XMPP COMMUNICATION PROTOCOL BOTTLENECKS IN INSTANT MESSAGING MODULES BY IMPLEMENTING CUSTOM TCP SOCKET KEEP-ALIVE HEARTBEATS AND BINARY PAYLOAD COMPRESSION. ESTABLISHED ENTERPRISE CI/CD PIPELINES USING JENKINS AND FASTLANE, AUTOMATING TESTFLIGHT DISTRIBUTION AND APP STORE REVIEW SUBMISSIONS. SYSTEM DIAGNOSTICS AND CAPABILITY RADAR. I AM NOT MERELY A CODE GENERATOR. I AM A FULL-CYCLE, PRODUCT-MINDED ENGINEER WITH DEEP ARCHITECTURAL JUDGMENT. I DEPLOY CLOUD-NATIVE MICROSERVICES USING DOCKER AND KUBERNETES. I OPTIMIZE POSTGRESQL QUERY EXECUTION PLANS. I MANAGE REDIS CLUSTERS FOR DISTRIBUTED LOCKS. I BUILD REACT AND NEXT.JS SERVER-SIDE RENDERED WEBSITES WITH TAILWIND CSS FOR MAXIMUM CORE WEB VITALS SCORES. BACKEND EXPERTISE ANCHORED IN GOLANG GOFRAME FOR MAXIMUM CONCURRENCY AND NODE.JS PYTHON FOR AGILE SCRIPTING. THE NEXT DECADE BELONGS TO THOSE WHO CAN SEAMLESSLY BRIDGE THE GAP BETWEEN STOCHASTIC AI CAPABILITIES AND DETERMINISTIC SOFTWARE ENGINEERING. CURRENT STATUS: OPEN FOR STRATEGIC FREELANCE OPPORTUNITIES, HIGH-IMPACT ARCHITECTURAL CONSULTING, AND REMOTE COLLABORATIONS IN 2026. WAITING FOR INPUT. END OF TRANSMISSION.`;

export type ProjectData = {
  id: string;
  themeColor: "emerald" | "cyan" | "blue";
  icon: LucideIcon;
  title: string;
  tag: string;
  tags: string[];
  description: {
    label1: string;
    text1: string;
    label2: string;
    text2: string;
    label3: string;
    scrambleText3: string;
  };
};

export const PROJECTS: ProjectData[] = [
  {
    id: "sdac",
    themeColor: "emerald",
    icon: Smartphone,
    title: "SDAC Poster Editor",
    tag: "Mobile Native",
    tags: ["[Hybrid_Mobile]", "[Go]", "[Canvas_API]"],
    description: {
      label1: "Problem:", text1: "Complex mobile drag-and-drop editor with rendering inconsistencies across devices.",
      label2: "Arch:", text2: "Hybrid approach. Frontend Canvas for UI + Go backend for exact image compositing.",
      label3: "Result:", scrambleText3: "Zero layout bugs."
    }
  },
  {
    id: "gaap",
    themeColor: "cyan",
    icon: ShieldCheck,
    title: "GAAP FinSystem",
    tag: "AI/FinTech",
    tags: ["[GoFrame]", "[Next.js_15]", "[gRPC]"],
    description: {
      label1: "Focus:", text1: 'Exploring the engineering boundaries of LLM "Vibe Coding".',
      label2: "Guardrails:", text2: "Strict Go-level type systems & property-based testing to intercept AI hallucinations.",
      label3: "Result:", scrambleText3: "Safe, reliable multi-currency accounting MVP."
    }
  },
  {
    id: "dify",
    themeColor: "blue",
    icon: Layers,
    title: "Enterprise AI Gateway",
    tag: "Infrastructure",
    tags: ["[Dify]", "[SSO/RBAC]", "[Python]"],
    description: {
      label1: "Task:", text1: "Intranet deployment & adaptation of open-source Dify platform.",
      label2: "Arch:", text2: "Global SSO gateway + RBAC reverse proxy for 1000+ users.",
      label3: "Result:", scrambleText3: "Highly secure, low-intrusion enterprise AI."
    }
  }
];

export const SKILLS = [
  "Swift_Obj-C", "React_Native", "React_Next.js", "Tailwind_CSS",
  "Golang_GoFrame", "Node.js_Python", "Docker_CICD", "gRPC_Microservices",
  "LLM_API", "RAG_Agent", "Dify_Custom", "AI_Code_Auditing"
];

export const WHY_ME_REASONS = [
  {
    id: "01",
    title: "01. No Translation Lost",
    delay: 0,
    desc: "Former Tech Director. Give me a business goal; I'll break it down into a technical WBS. Zero spoon-feeding required."
  },
  {
    id: "02",
    title: "02. Design to Code",
    delay: 200,
    desc: "High standard for UI aesthetics (Sketch/Figma). I deliver the full pipeline from frontend interaction to backend logic."
  },
  {
    id: "03",
    title: "03. Honest Estimation",
    delay: 400,
    desc: "I know which AI features are pseudo-needs. I provide honest estimations to prevent expensive technical debt."
  }
];

export const SOCIAL_LINKS = {
  github: "https://github.com/gin-melodic",
  twitter: "https://twitter.com/melodicgin",
  blog: "https://antinomy.me"
};

export const CONTACT_EMAIL = "hello@ginmel.ai";
